name: HTML Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello, World!"
      - name: Print some lines
        run: |
          echo "Line 1"
          echo "Line 2"
          echo "Line 3"


        