name: Print pull request context
on: workflow_dispatch
jobs:
  print-pr-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Context
        run: 
          echo "${{ toJson(github) }}" 